name: Deploy to Starthost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Roman via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./roman/
          server-dir: /roman/
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
            **/README.md
            **/docs/**
            **/scripts/**

      - name: Deploy Roman Preview via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./roman/
          server-dir: /preview/roman/
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
            **/README.md
            **/docs/**
            **/scripts/**

      - name: Deploy Preview via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./preview/
          server-dir: /preview/
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
